[versions]
gson = "2.11.0"

# plugins
intellij = "1.17.4"
kotlin = "2.1.20"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
intellij = { id = "org.jetbrains.intellij", version.ref = "intellij" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
